### ISSUE TITLE
Latest CLUES version behavior

### ISSUE THREAD

**Issue by vasilipankratov** [standard-aaron/clues#4]
Hi Aaron!
I observe some behavior of the latest CLUES version which is rather different from the older version and somehow (based on previous knowledge about the LCT allele) I tend to think that the older version is doing the job better.

I ran CLUES for rs4988235 using the same anc/mut output of relate v1.1 in two ways: producing SampleBranchLengths.sh output in a) binary format and b) in the newick format.

Next in the a) case I directly ran inference.py from the **latest** CLUES version (downloaded on 13th September) specifying the .timeb  file under --times option. In the case of b) I first applied extract_coals.py from the **previous** CLUES version using the newick file as input and then ran the inference.py from the **previous** CLUES version using the anc.npy and der.npy files as input for the --times option. 

I get substantially different results in the two cases: logLR: 23.8678 vs 74.5807, s 0.00784 vs 0.01860 for a) and b) respectively and an allele frequency trajectory much more concordant with what is published in the CLUES paper under scenario  b). The running time of the a) scenario a) is also several fold higher.

So is there anything obvious I'm doing wrong here? One thing which is unclear to me is that the newer version of CLUES is not requiring the haps file as did the older version. Is that ok or am I missing something?

Best,

Vasili

**Comment by standard-aaron** [comment]
It's correct that it should not longer require .haps.

I'm not sure i know how to determine exactly the source of the discrepany. Unless you are analyzing the same population/samples as we did in our paper, I don't think we should necessarily expect the logLRs or s estimates to be the same.

You might want to try playing with the --df parameter: that controls the degree of frequency discretization in the HMM. Smaller values run faster.

Aaron

**Comment by vasilipankratov** [comment]
Thanks a lot for a prompt reply!
I agree that we wouldn't expect my result to replicate yours since those were obtained on different datasets. However, given that I'm dealing with a European population I would still expect a strong signal for LCT and it is much stronger in settings b). Moreover, the allele frequency trajectory makes much more sense in b (see the plots attached). Ok, I'll try some other SNPs for which I have something to expect and if I still observe the discrepancy I'll get back to you. 

BTW, I see there a few more new options in the latest version like --changePts. Where can I learn what do those options do?
[LCT_Estonia_b.pdf](https://github.com/35ajstern/clues/files/5385648/LCT_Estonia_b.pdf)
[LCT_Estonia_a.pdf](https://github.com/35ajstern/clues/files/5385649/LCT_Estonia_a.pdf)

Thanks!

Vasili

**Comment by vasilipankratov** [comment]
Thanks a lot for a prompt reply!
I agree that we wouldn't expect my result to replicate yours since those were obtained on different datasets. However, given that I'm dealing with a European population I would still expect a strong signal for LCT and it is much stronger in settings b). Moreover, the allele frequency trajectory makes much more sense in b (see the plots attached). Ok, I'll try some other SNPs for which I have something to expect and if I still observe the discrepancy I'll get back to you. 

BTW, I see there a few more new options in the latest version like --changePts. Where can I learn what do those options do?
[LCT_Estonia_b.pdf](https://github.com/35ajstern/clues/files/5385648/LCT_Estonia_b.pdf)
[LCT_Estonia_a.pdf](https://github.com/35ajstern/clues/files/5385649/LCT_Estonia_a.pdf)

Thanks!

Vasili
